/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.CadastroFornecedorController;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author marcos.santos
 */
public class TelaCadastroFornecedor extends javax.swing.JFrame {

    //criando campo controller
    private final CadastroFornecedorController controller;



    public TelaCadastroFornecedor() {
        initComponents();

        this.setResizable(false);

        //controller esta passando view como parametro
        controller = new CadastroFornecedorController(this);

        //inicia essa tela no centro
        this.setLocationRelativeTo(null);

        //chama o metodo iniciar
        this.iniciar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        txtId = new JTextField();
        lblFornecedorNome = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        txtFornecedor = new JTextField();
        btnPesquisar = new JButton();
        btnSalvar = new JButton();
        btnVoltar1 = new JButton();
        btnExcluir = new JButton();
        btnEditar = new JButton();
        btnNovo = new JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaFornecedor = new JTable();
        jLblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("CADASTRO DE FORNECEDOR");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, -1));

        txtId.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtId.setEnabled(false);
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 100, -1));

        lblFornecedorNome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblFornecedorNome.setForeground(new java.awt.Color(255, 255, 255));
        lblFornecedorNome.setText("FORNECEDORNOME:");
        getContentPane().add(lblFornecedorNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, 30));

        lblID.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblID.setForeground(new java.awt.Color(255, 255, 255));
        lblID.setText("ID:");
        getContentPane().add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 30));

        txtFornecedor.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        getContentPane().add(txtFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 180, -1));

        btnPesquisar.setBackground(new java.awt.Color(30, 129, 176));
        btnPesquisar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setText("PESQUISAR");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 180, 110, 40));

        btnSalvar.setBackground(new java.awt.Color(30, 129, 176));
        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 240, 110, 40));

        btnVoltar1.setBackground(new java.awt.Color(30, 129, 176));
        btnVoltar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVoltar1.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar1.setText("VOLTAR");
        btnVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 240, 110, 40));

        btnExcluir.setBackground(new java.awt.Color(30, 129, 176));
        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 240, 110, 40));

        btnEditar.setBackground(new java.awt.Color(30, 129, 176));
        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 180, 110, 40));

        btnNovo.setBackground(new java.awt.Color(30, 129, 176));
        btnNovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNovo.setForeground(new java.awt.Color(255, 255, 255));
        btnNovo.setText("NOVO");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 180, 110, 40));

        jTabelaFornecedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTabelaFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "fornecedornome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabelaFornecedor.setAutoscrolls(false);
        jTabelaFornecedor.setFocusable(false);
        jTabelaFornecedor.setRequestFocusEnabled(false);
        jTabelaFornecedor.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTabelaFornecedor.getTableHeader().setReorderingAllowed(false);
        jTabelaFornecedor.setUpdateSelectionOnSort(false);
        jTabelaFornecedor.setVerifyInputWhenFocusTarget(false);
        jTabelaFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaFornecedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabelaFornecedor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 1250, 360));

        jLblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/PARTE INTERNA2.png"))); // NOI18N
        getContentPane().add(jLblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabelaFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaFornecedorMouseClicked
        // TODO add your handling code here:
        setModelo();
    }//GEN-LAST:event_jTabelaFornecedorMouseClicked

    private void btnVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltar1ActionPerformed
        //tente chamar a tela cadastro equipamento
        try
        {

            this.dispose();

            TelaCadastroEquipamento telacadequipamento = new TelaCadastroEquipamento();
            telacadequipamento.setVisible(true);

        }
        //se não conseguir pegue a excesão e mostre a mensagem na tela junto com a excesão
        catch(Exception ex)
        {

            JOptionPane.showMessageDialog(null, "Error ao chamar a tela cadastro equipamento!" + ex);

        }
    }//GEN-LAST:event_btnVoltar1ActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        //controller chama metodo deletar fabricante
        controller.deletar();

        iniciar();

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        //controller chama metodo salvar fornecedor
        controller.salvarFornecedor();

        iniciar();
    }//GEN-LAST:event_btnSalvarActionPerformed
    public void setModelo()
    {

        int setar = jTabelaFornecedor.getSelectedRow();

        txtId.setText(jTabelaFornecedor.getModel().getValueAt(setar, 0).toString());
        txtFornecedor.setText(jTabelaFornecedor.getModel().getValueAt(setar, 1).toString());

    }public void desbloquearCampos()
    {

        getTxtFornecedor().setEnabled(true);

        btnEditar.setEnabled(true);
        btnExcluir.setEnabled(true);
        btnSalvar.setEnabled(true);
        btnPesquisar.setEnabled(true);

    }
    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        //ao clickar chama o helper em novo seta todos os campos como true
        desbloquearCampos();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        //controller chama metodo update forncedor
        controller.updateFornecedor();

        iniciar();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed

    }//GEN-LAST:event_btnPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroFornecedor().setVisible(true);
            }
        });
    }

    //getters e setters
    public static JButton getBtnEditar() {
        return btnEditar;
    }

    public static void setBtnEditar(JButton btnEditar) {
        TelaCadastroFornecedor.btnEditar = btnEditar;
    }

    public static JButton getBtnExcluir() {
        return btnExcluir;
    }

    public static void setBtnExcluir(JButton btnExcluir) {
        TelaCadastroFornecedor.btnExcluir = btnExcluir;
    }

    public static JButton getBtnNovo() {
        return btnNovo;
    }

    public static void setBtnNovo(JButton btnNovo) {
        TelaCadastroFornecedor.btnNovo = btnNovo;
    }

    public static JButton getBtnPesquisar() {
        return btnPesquisar;
    }

    public static void setBtnPesquisar(JButton btnPesquisar) {
        TelaCadastroFornecedor.btnPesquisar = btnPesquisar;
    }

    public static JButton getBtnSalvar() {
        return btnSalvar;
    }

    public static void setBtnSalvar(JButton btnSalvar) {
        TelaCadastroFornecedor.btnSalvar = btnSalvar;
    }

    public static JButton getBtnVoltar1() {
        return btnVoltar1;
    }

    public static void setBtnVoltar1(JButton btnVoltar1) {
        TelaCadastroFornecedor.btnVoltar1 = btnVoltar1;
    }

    public static JTextField getTxtFornecedor() {
        return txtFornecedor;
    }

    public static void setTxtFornecedor(JTextField txtFornecedor) {
        TelaCadastroFornecedor.txtFornecedor = txtFornecedor;
    }

    public static JTextField getTxtId() {
        return txtId;
    }

    public static void setTxtId(JTextField txtId) {
        TelaCadastroFornecedor.txtId = txtId;
    }

    public void iniciar()
    {

            //impede o usuario de mover as colunas para reoodena-las
            jTabelaFornecedor.getTableHeader().setReorderingAllowed(false);

            //chama este metodo do controller
            controller.tabelaFornecedor();

            jTabelaFornecedor.setRowSelectionAllowed(true);

            //impessa o jtable de se auto redimensionar
            jTabelaFornecedor.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

            //as linhas abaixo define o tamanho das colunas da tabela
            //tabela pegue o modelo de coluna, pegue a coluna zero e sete a largura
            jTabelaFornecedor.getColumnModel().getColumn(0).setPreferredWidth(622);
            jTabelaFornecedor.getColumnModel().getColumn(1).setPreferredWidth(622);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static JButton btnEditar;
    public static JButton btnExcluir;
    public static JButton btnNovo;
    public static JButton btnPesquisar;
    public static JButton btnSalvar;
    public static JButton btnVoltar1;
    private javax.swing.JLabel jLblFundo;
    private javax.swing.JScrollPane jScrollPane1;
    public static JTable jTabelaFornecedor;
    private javax.swing.JLabel lblFornecedorNome;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblTitulo;
    public static JTextField txtFornecedor;
    public static JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
