package view;

import controller.CadastroTipoEquipamentoController;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

public class TelaCadastroTipoEquipamento extends javax.swing.JFrame {

    public void setModelo()
    {

        int setar = jTabelaTipoEquipamento.getSelectedRow();

        txtId.setText(jTabelaTipoEquipamento.getModel().getValueAt(setar, 0).toString());
        txtTipoEquipamento.setText(jTabelaTipoEquipamento.getModel().getValueAt(setar, 1).toString());

    }public void desbloquearCampos()
    {

        getTxtTipoEquipamento().setEnabled(true);

        btnEditar.setEnabled(true);
        btnExcluir.setEnabled(true);
        btnSalvar.setEnabled(true);
        btnPesquisar.setEnabled(true);

    }

    //criando campo controller
    private final CadastroTipoEquipamentoController controller;



    public TelaCadastroTipoEquipamento() {
        initComponents();

        this.setResizable(false);

        //controller esta passando view como parametro
        controller = new CadastroTipoEquipamentoController(this);



        //inicia essa tela no centro
        this.setLocationRelativeTo(null);

        //chama o metodo iniciar
        this.iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaTipoEquipamento = new JTable();
        txtId = new JTextField();
        lblID = new javax.swing.JLabel();
        lblTipoEquipamento = new javax.swing.JLabel();
        txtTipoEquipamento = new JTextField();
        btnSalvar = new JButton();
        btnExcluir = new JButton();
        btnVoltar1 = new JButton();
        btnPesquisar = new JButton();
        btnEditar = new JButton();
        btnNovo = new JButton();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabelaTipoEquipamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTabelaTipoEquipamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "tipoequipamento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabelaTipoEquipamento.setAutoscrolls(false);
        jTabelaTipoEquipamento.setFocusable(false);
        jTabelaTipoEquipamento.setRequestFocusEnabled(false);
        jTabelaTipoEquipamento.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTabelaTipoEquipamento.getTableHeader().setReorderingAllowed(false);
        jTabelaTipoEquipamento.setUpdateSelectionOnSort(false);
        jTabelaTipoEquipamento.setVerifyInputWhenFocusTarget(false);
        jTabelaTipoEquipamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaTipoEquipamentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabelaTipoEquipamento);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 1250, 360));

        txtId.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtId.setEnabled(false);
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 100, -1));

        lblID.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblID.setForeground(new java.awt.Color(255, 255, 255));
        lblID.setText("ID:");
        getContentPane().add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 30));

        lblTipoEquipamento.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTipoEquipamento.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoEquipamento.setText("TIPOEQUIPAMENTO:");
        getContentPane().add(lblTipoEquipamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, 30));

        txtTipoEquipamento.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        getContentPane().add(txtTipoEquipamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 180, -1));

        btnSalvar.setBackground(new java.awt.Color(30, 129, 176));
        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 240, 110, 40));

        btnExcluir.setBackground(new java.awt.Color(30, 129, 176));
        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 240, 110, 40));

        btnVoltar1.setBackground(new java.awt.Color(30, 129, 176));
        btnVoltar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVoltar1.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar1.setText("VOLTAR");
        btnVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 240, 110, 40));

        btnPesquisar.setBackground(new java.awt.Color(30, 129, 176));
        btnPesquisar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setText("PESQUISAR");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 180, 110, 40));

        btnEditar.setBackground(new java.awt.Color(30, 129, 176));
        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 180, 110, 40));

        btnNovo.setBackground(new java.awt.Color(30, 129, 176));
        btnNovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNovo.setForeground(new java.awt.Color(255, 255, 255));
        btnNovo.setText("NOVO");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 180, 110, 40));

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/PARTE INTERNA2.png"))); // NOI18N
        getContentPane().add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabelaTipoEquipamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaTipoEquipamentoMouseClicked
        // TODO add your handling code here:
        setModelo();
    }//GEN-LAST:event_jTabelaTipoEquipamentoMouseClicked

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        //controller chama metodo salvar tipo equipamento
        controller.salvarTipoEquipamento();

        iniciar();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        //controller chama metodo deletar tipo equipamento
        controller.deletar();

        iniciar();

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltar1ActionPerformed
        //tente chamar a tela cadastro equipamento
        try
        {

            this.dispose();

            TelaCadastroEquipamento telacadequipamento = new TelaCadastroEquipamento();
            telacadequipamento.setVisible(true);

        }
        //se não conseguir pegue a excesão e mostre a mensagem na tela junto com a excesão
        catch(Exception ex)
        {

            JOptionPane.showMessageDialog(null, "Error ao chamar a tela cadastro equipamento!" + ex);

        }
    }//GEN-LAST:event_btnVoltar1ActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed

    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        //controller chama metodo update tipo equipamento
        controller.updateTipoEquipamento();

        iniciar();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        //ao clickar chama o helper em novo seta todos os campos como true
        desbloquearCampos();
    }//GEN-LAST:event_btnNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroTipoEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroTipoEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroTipoEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroTipoEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroTipoEquipamento().setVisible(true);
            }
        });
    }

    //getters e setters
    public static JButton getBtnEditar() {
        return btnEditar;
    }

    public static void setBtnEditar(JButton btnEditar) {
        TelaCadastroTipoEquipamento.btnEditar = btnEditar;
    }

    public static JButton getBtnExcluir() {
        return btnExcluir;
    }

    public static void setBtnExcluir(JButton btnExcluir) {
        TelaCadastroTipoEquipamento.btnExcluir = btnExcluir;
    }

    public static JButton getBtnNovo() {
        return btnNovo;
    }

    public static void setBtnNovo(JButton btnNovo) {
        TelaCadastroTipoEquipamento.btnNovo = btnNovo;
    }

    public static JButton getBtnSalvar() {
        return btnSalvar;
    }

    public static void setBtnSalvar(JButton btnSalvar) {
        TelaCadastroTipoEquipamento.btnSalvar = btnSalvar;
    }

    public static JButton getBtnVoltar1() {
        return btnVoltar1;
    }

    public static void setBtnVoltar1(JButton btnVoltar1) {
        TelaCadastroTipoEquipamento.btnVoltar1 = btnVoltar1;
    }

    public static JTable getjTabelaTipoEquipamento() {
        return jTabelaTipoEquipamento;
    }

    public static void setjTabelaTipoEquipamento(JTable jTabelaTipoEquipamento) {
        TelaCadastroTipoEquipamento.jTabelaTipoEquipamento = jTabelaTipoEquipamento;
    }

    public static JTextField getTxtId() {
        return txtId;
    }

    public static void setTxtId(JTextField txtId) {
        TelaCadastroTipoEquipamento.txtId = txtId;
    }

    public static JTextField getTxtTipoEquipamento() {
        return txtTipoEquipamento;
    }

    public static void setTxtTipoEquipamento(JTextField txtTipoEquipamento) {
        TelaCadastroTipoEquipamento.txtTipoEquipamento = txtTipoEquipamento;
    }

    public void iniciar()
    {

            //impede o usuario de mover as colunas para reoodena-las
            jTabelaTipoEquipamento.getTableHeader().setReorderingAllowed(false);

            //chama este metodo do controller
            controller.tabelaTipoEquipamento();

            jTabelaTipoEquipamento.setRowSelectionAllowed(true);

            //impessa o jtable de se auto redimensionar
            jTabelaTipoEquipamento.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

            //as linhas abaixo define o tamanho das colunas da tabela
            //tabela pegue o modelo de coluna, pegue a coluna zero e sete a largura
            jTabelaTipoEquipamento.getColumnModel().getColumn(0).setPreferredWidth(622);
            jTabelaTipoEquipamento.getColumnModel().getColumn(1).setPreferredWidth(622);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static JButton btnEditar;
    public static JButton btnExcluir;
    public static JButton btnNovo;
    public static JButton btnPesquisar;
    public static JButton btnSalvar;
    public static JButton btnVoltar1;
    private javax.swing.JScrollPane jScrollPane1;
    public static JTable jTabelaTipoEquipamento;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblTipoEquipamento;
    public static JTextField txtId;
    public static JTextField txtTipoEquipamento;
    // End of variables declaration//GEN-END:variables
}
